<?php
return array(
    'Simukti\Module'                      => __DIR__ . '/Module.php',
    'Simukti\Controller\Article'          => __DIR__ . '/src/Simukti/Controller/Article.php',
    'Simukti\Controller\Async'            => __DIR__ . '/src/Simukti/Controller/Async.php',
    'Simukti\Controller\BaseController'   => __DIR__ . '/src/Simukti/Controller/BaseController.php',
    'Simukti\Controller\Internal'         => __DIR__ . '/src/Simukti/Controller/Internal.php',
    'Simukti\Controller\Misc'             => __DIR__ . '/src/Simukti/Controller/Misc.php',
    'Simukti\Controller\Page'             => __DIR__ . '/src/Simukti/Controller/Page.php',
    'Simukti\Factory\ApiService'          => __DIR__ . '/src/Simukti/Factory/ApiService.php',
    'Simukti\Factory\AsyncController'     => __DIR__ . '/src/Simukti/Factory/AsyncController.php',
    'Simukti\Factory\FeedService'         => __DIR__ . '/src/Simukti/Factory/FeedService.php',
    'Simukti\Factory\FlickrService'       => __DIR__ . '/src/Simukti/Factory/FlickrService.php',
    'Simukti\Factory\GistService'         => __DIR__ . '/src/Simukti/Factory/GistService.php',
    'Simukti\Factory\GithubService'       => __DIR__ . '/src/Simukti/Factory/GithubService.php',
    'Simukti\Factory\MiscController'      => __DIR__ . '/src/Simukti/Factory/MiscController.php',
    'Simukti\Factory\PageRoutesService'   => __DIR__ . '/src/Simukti/Factory/PageRoutesService.php',
    'Simukti\Factory\SitemapService'      => __DIR__ . '/src/Simukti/Factory/SitemapService.php',
    'Simukti\Service\Api'                 => __DIR__ . '/src/Simukti/Service/Api.php',
    'Simukti\Service\BaseService'         => __DIR__ . '/src/Simukti/Service/BaseService.php',
    'Simukti\Service\Feed'                => __DIR__ . '/src/Simukti/Service/Feed.php',
    'Simukti\Service\Flickr'              => __DIR__ . '/src/Simukti/Service/Flickr.php',
    'Simukti\Service\Gist'                => __DIR__ . '/src/Simukti/Service/Gist.php',
    'Simukti\Service\Github'              => __DIR__ . '/src/Simukti/Service/Github.php',
    'Simukti\Service\HttpParser'          => __DIR__ . '/src/Simukti/Service/HttpParser.php',
    'Simukti\Service\PageRoutes'          => __DIR__ . '/src/Simukti/Service/PageRoutes.php',
    'Simukti\Service\Sitemap'             => __DIR__ . '/src/Simukti/Service/Sitemap.php',
    'Simukti\View\Helper\ArticleRecent'   => __DIR__ . '/src/Simukti/View/Helper/ArticleRecent.php',
    'Simukti\View\Helper\Disqus'          => __DIR__ . '/src/Simukti/View/Helper/Disqus.php',
    'Simukti\View\Helper\Flickr'          => __DIR__ . '/src/Simukti/View/Helper/Flickr.php',
    'Simukti\View\Helper\GistParser'      => __DIR__ . '/src/Simukti/View/Helper/GistParser.php',
    'Simukti\View\Helper\GoogleAnalytics' => __DIR__ . '/src/Simukti/View/Helper/GoogleAnalytics.php',
    'Simukti\View\Helper\Livefyre'        => __DIR__ . '/src/Simukti/View/Helper/Livefyre.php',
    'Simukti\View\Helper\Pages'           => __DIR__ . '/src/Simukti/View/Helper/Pages.php',
);