<?php /* generic backdrop template */ ?>
<div id="backdrop" class="backdrop">
    <div class="container">
        <div class="row">
            <div class="span2 offset2">
                <h1><?php echo $this->main_title; ?></h1>
            </div>
            
            <?php if(isset($this->right_title)) : ?>
            <div class="span6 backdrop-right-note visible-desktop">
                <p class="backdrop-quote">
                    <?php echo $this->right_title; ?>
                </p>
            </div>
            <?php endif; ?>
            
        </div>
    </div>
</div>