<div id="backdrop" class="backdrop">
    <div class="container">
        <div class="row">
            <div class="span8 offset2">
                <h1><?php echo $this->message ?></h1>
            </div>
        </div>
    </div>
</div>

<?php if (isset($this->display_exceptions) && $this->display_exceptions) : ?>
    <div class="container">
        <div class="row">
            <div class="span8 offset2">
                <div class="post single-post">
                    <div class="post-content">
                        <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                            <hr/>
                            <!--<h2>Additional information :</h2> -->
                            <h3><?php echo get_class($this->exception); ?></h3>
                            <dl>
                                <dt>File :</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                                </dd>
                                <dt>Message :</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                                </dd>
                                <dt>Stack trace :</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                                </dd>
                            </dl>
                            <?php
                            $e = $this->exception->getPrevious();
                            if ($e) :
                                ?>
                                <hr/>
                                <h2>Previous exceptions :</h2>
                                <ul class="unstyled">
                                    <?php while ($e) : ?>
                                        <li>
                                            <h3><?php echo get_class($e); ?></h3>
                                            <dl>
                                                <dt>File :</dt>
                                                <dd>
                                                    <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                                </dd>
                                                <dt>Message :</dt>
                                                <dd>
                                                    <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                                                </dd>
                                                <dt>Stack trace :</dt>
                                                <dd>
                                                    <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                                                </dd>
                                            </dl>
                                        </li>
                                        <?php $e = $e->getPrevious(); endwhile; ?>
                                </ul>
                            <?php endif; ?>
                        <?php else: ?>
                        <h3>No Exception available :</h3>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
