<?php $pageCategory = $this->pageCategory; ?>

<?php if (count($pageCategory)) : ?>
    
    <li class="dropdown">
        <?php if ($pageCategory['slug'] == 'internal') : ?>
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <i class="icon-th-list icon-white"></i> <?php echo $pageCategory['name']; ?><b class="caret"></b>
            </a>
        <?php endif; ?>
        
        <ul id="swatch-menu" class="dropdown-menu">
            <?php foreach ($pageCategory['pages'] as $page) : ?>
                <li><a href="<?php echo $this->url($page['slug']); ?>">
                        <?php $icon = ( isset($this->iconMaps[$page['slug']]) ) ? $this->iconMaps[$page['slug']] : 'icon-file'; ?>
                        <i class="<?php echo $icon; ?>"></i> <?php echo $page['title']; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    
<?php endif; ?>