<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
             $this->headTitle('Sarjono Mukti Aji')->setDefaultAttachOrder('APPEND')->setSeparator(' - ')->setAutoEscape(true);
             $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
             $this->headMeta()->prependName('keywords', 'sarjono mukti aji, simukti');
             $this->headLink(array('rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 
                                   'href' => $this->basePath() . '/assets/img/favicon.ico'));
             $this->headLink()->prependStylesheet($this->basePath() . '/assets/css/simukti-network.css??201307061017'); 
             
             echo $this->headTitle();
             echo $this->headMeta();
             echo $this->headLink();
             echo $this->googleAnalytics();
        ?>
    </head>
    <body class="simukti">
        <header>
            <div class="navbar navbar-static-top navbar-inverse">
                <div class="navbar-inner">
                    <div class="container">
                        <div class="row">
                            <div class="span8 offset2">
                                <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" style="margin: 0 10px 0 0;"> <span class="icon-plus icon-white"></span> </a>
                                <a href="<?php echo $this->url('home') ?>" class="brand">siMukti.Net</a>
                                <div id="main-menu" class="nav-collapse">
                                    <ul id="main-menu-right" class="nav pull-right">
                                        
                                        <?php $pageData = $this->pages()->getPages(); ?>
                                        <?php $iconMaps = $this->pages()->getIconMaps(); ?>
                                        <?php foreach($pageData['data'] as $pageCategory) : ?>
                                            <?php echo $this->partial('layout/_navigation', array(
                                                'pageCategory' => $pageCategory,
                                                'iconMaps' => $iconMaps
                                            )); ?>
                                        <?php  endforeach; ?>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section>
            <?php echo $this->content; ?>
        </section>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span8 offset2">
                        <div class="footer">
                            <p>
                                <?php $current = date('Y'); $year = ($current == 2009) ? $current : sprintf("2009 - %s", $current); ?>
                                Copyright &copy; <?php echo  $year; ?> &middot; <a href="<?php echo $this->url('home'); ?>">Sarjono Mukti Aji</a>. 
                                Powered by <a href="http://framework.zend.com/" target="_blank">ZendFramework v<?php echo \Zend\Version\Version::VERSION; ?></a>. 
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    <?php
        if(PRODUCTION && ($_SERVER['SERVER_NAME'] !== DEV_SERVER_NAME)) {
            $this->headScript()->prependFile('//code.jquery.com/jquery-1.8.0.min.js');
        } else {
            $this->headScript()->prependFile('/assets/js/jquery.js');
        }
        $this->headScript()->appendFile($this->basePath() . '/assets/js/simukti-network.js');
        
        echo $this->headScript(); 
        echo $this->inlineScript();
    ?>
    </body>
</html>
