<?php 
if($this->tags) {
    $tags = array();
    foreach($this->tags['data'] as $tag) {
        $tags[] = strtolower($tag['name']);
    }
    $this->headMeta(implode(', ', $tags), 'keywords');
}
$msg = 'I\'m Sarjono Mukti Aji, and this is my official site (and playground). 
        Respecting Open Source, Open Mind, and Meritocracy, 
        this site (in Indonesian / English) is about my views, technical notes, and my fun things.';
$this->headMeta($msg, 'description');
?>

<div class="row">
    <div class="col-lg-12">
        <div class="intro">
            <p> <?php echo $msg; ?> </p>
            <p class="social">
                <a href="https://github.com/simukti" class="link-github" title="github.com/simukti" rel="follow"><i class="icon-github-sign"></i></a>
                <a href="https://twitter.com/simukti" class="link-twitter" title="twitter.com/simukti" rel="follow"><i class="icon-twitter-sign"></i></a>
                <a href="https://www.linkedin.com/in/simukti" class="link-linkedin" title="linkedin.com/in/simukti" rel="follow"><i class="icon-linkedin-sign"></i></a>
                <a href="mailto:me@simukti.net" class="link-email" title="me@simukti.net"><i class="icon-envelope"></i></a>
            </p>
        </div>
    </div>
</div>

<div class="content">
    <?php echo $this->articleRecent(); ?>
    <?php echo $this->render('simukti/xhr/frontpage'); ?>
</div>