<?php if($this->result) : ?>

<?php 
$page        = $this->result['data'];
$title       = $page['title'];
$keywords    = strtolower($page['keywords']);
$description = preg_replace('/\[gist\]([0-9a-z]+)\[\/gist\]/', '', substr(strip_tags($page['content']), 0, 250));

$this->headTitle($title);
$this->headMeta()->appendName('keywords', $keywords);
$this->headMeta()->appendName('description', $description);
?>

<div class="content single-view">
    <div class="single-view-header">
        <h1 id="content-title"><?php echo $title; ?></h1>
    </div>
    <div class="single-view-content">
        <?php echo $this->gistParser($page['content']); ?>
    </div>
</div>

<?php endif; ?>