<?php if (count($this->articles)) : ?>

    <div class="list-div">
        <h2><i class="<?php echo $this->icon; ?>"></i> <?php echo $this->title; ?></h2>
        <table class="table table-condensed table-hover list-table">
            <tbody>
                <?php foreach ($this->articles as $article): ?>
                    <?php
                    $date = new \DateTime($article['createdAt']);
                    $formatedDate = $date->format('Y/m/d');
                    $url = $this->url('article_view', array(
                            'year'  => $date->format('Y'),
                            'month' => $date->format('m'),
                            'day'   => $date->format('d'),
                            'slug'  => $article['slug']
                        ));
                    ?>
                    <tr>
                        <td class="list-title"><a href="<?php echo $url; ?>" rel="follow"><?php echo $article['title']; ?></a></td>
                        <td class="list-note hidden-xs"><?php echo $formatedDate; ?></td>
                    </tr>
                <?php endforeach; ?>
                
                <?php if(isset($this->show_archive_button) && $this->show_archive_button == false) : ?>
                <?php else :?>
                <tr>
                    <td class="list-note" colspan="2">
                        <a class="pull-right btn btn-sm btn-info" href="<?php echo $this->url('article_archive');?>" rel="follow">Archive <i class="icon-arrow-right"></i></a>
                    </td>
                </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
    
<?php endif; ?>