<?php if($this->result) : ?>

<?php 
$title = 'Article / Archive';
$this->headTitle($title); 
?>

<div class="content single-view">
    <div class="single-view-header">
        <h1 id="content-title">
            <?php echo $title; ?>
        </h1>
    </div>
    <div class="list-div">
        <?php foreach($this->result['data'] as $archive) : ?>
            <?php echo $this->render('simukti/article/_list', array(
                'title'     => $archive['year'],
                'articles'  => $archive['articles'],
                'show_archive_button' => false,
                'icon'      => 'icon-calendar'
            ), array('force_canonical' => true)); ?>
        <?php endforeach; ?>
    
    <div class="single-view-header">
        <h1 id="content-title">
            Article / Tag
        </h1>
    </div>
    <div class="list-div">
        <h2><i class="icon-tags"></i> Tags</h2>
        <p>
            <?php foreach($this->tags['data'] as $tag) : ?>
                <a class="btn btn-sm btn-info" href="<?php echo $this->url('article_tag', array(
                    'slug' => $tag['slug']
                    ), array('force_canonical' => true));?>" rel="follow"> <i class="icon-tags"></i> <?php echo sprintf("%s (%s)", $tag['name'], $tag['articleCount']); ?> 
                </a>
            <?php endforeach;?>
        </p>
    </div>
    </div>
</div>

<?php endif; ?>