<?php if($this->result) : ?>

<?php 
$data = $this->result['data']; 
$date = new \DateTime($data['createdAt']);
$tempDate = $date->format('Y/m/d H:i');
$formatedDate = $tempDate . ' GMT' . substr($date->format('O'), 0, 3) . ':00';
$url = $this->url('article_view', array(
            'year'  => $date->format('Y'),
            'month' => $date->format('m'),
            'day'   => $date->format('d'),
            'slug'  => $data['slug']
        ), array('force_canonical' => true));
$shortUrl = $this->url('article_shortcut', array(
    'id' => $data['shortcut']
), array('force_canonical' => true));

$tags = array($data['keywords']);
foreach($data['tags'] as $tag) {
    $tags[] = strtolower($tag['name']);
}
$description = preg_replace('/\[gist\]([0-9a-z]+)\[\/gist\]/', '', substr(strip_tags($data['content']), 0, 250));

$this->headTitle($data['title']);
$this->headMeta()->appendName('keywords', implode(', ', $tags));
$this->headMeta()->appendName('description', $description);
$this->headLink(array(
    'rel' => 'canonical',
    'href' => $url
));
$this->headLink(array(
    'rel' => 'shortlink',
    'href' => $shortUrl
));
?>

<div class="content single-view" itemscope itemtype="http://schema.org/Article">
    <div class="single-view-header">
        <h1 id="content-title">
            <a itemprop="url" href="<?php echo $url; ?>"><span itemprop="name"> <?php echo $data['title']; ?> </span></a>
        </h1>
        <p>
            <span itemprop="author" itemscope itemtype="http://schema.org/Person"><span itemprop="name"><?php echo $data['user']['fullname']; ?></span></span>, 
            <span itemprop="datePublished" content="<?php echo $date->format('Y-m-d H:i'); ?>"> <?php echo $formatedDate; ?> </span>
        </p>
    </div>
    
    <div class="single-view-content">
        <?php echo $this->gistParser($data['content']); ?>
        <p>
            <a href="<?php echo $shortUrl; ?>" class="btn btn-info btn-sm"><i class="icon-share"></i> Article Shortcut </a>
        </p>
    </div>
    
    <div class="single-view-footer">
        <?php echo $this->livefyre($url, $data['title']); ?>
        <?php echo $this->articleRecent(); ?>
    </div>
</div>

<?php endif; ?>
