<?php if($this->result) : ?>

<?php 
$data = $this->result['data']; 
$date = new \DateTime($data['createdAt']);
$tempDate = $date->format('Y/m/d H:i');
$formatedDate = $tempDate . ' GMT' . substr($date->format('O'), 0, 3) . ':00';
$url = $this->url('article_view', array(
            'year'  => $date->format('Y'),
            'month' => $date->format('m'),
            'day'   => $date->format('d'),
            'slug'  => $data['slug']
        ));
$tags = array($data['keywords']);
foreach($data['tags'] as $tag) {
    $tags[] = strtolower($tag['name']);
}
$description = preg_replace('/\[gist\]([0-9a-z]+)\[\/gist\]/', '', substr(strip_tags($data['content']), 0, 250));

$this->headTitle($data['title']);
$this->headMeta()->appendName('keywords', implode(', ', $tags));
$this->headMeta()->appendName('description', $description);

//$right_title = sprintf("By <a href=\"%s\">%s</a>, %s", $this->url('home'), $data['user']['fullname'], $formatedDate);
?>

<div class="content single-view">
    <div class="single-view-header">
        <h1 id="content-title">
            <a href="<?php echo $this->serverUrl() . $url; ?>"> <?php echo $data['title']; ?> </a>
        </h1>
        <p> <?php echo $formatedDate; ?> </p>
    </div>
    
    <div class="single-view-content">
        <?php echo $this->gistParser($data['content']); ?>
        <p>
            <a href="<?php echo $this->url('article_shortcut', array('id' => $data['shortcut'])); ?>" 
               class="btn btn-info btn-sm"><i class="icon-share"></i> Article Shortcut
            </a>
        </p>
    </div>
    
    <div class="single-view-footer">
        <?php echo $this->livefyre($url, $data['title']); ?>
        <?php echo $this->articleRecent(); ?>
    </div>
</div>

<?php endif; ?>
